export enum ActionType {
    AUTH = "AUTH",
    LOGOUT = "LOGOUT",
    UPDATE_USER = "UPDATE_USER",
    UPDATE_FAVORITES = "UPDATE_FAVORITES",
    AUTH_ERROR = "AUTH_ERROR",
    CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR",
}